# Use the official Nginx image as a base
FROM nginx:alpine

# Copy the static HTML files into the container
COPY html /usr/share/nginx/html

# Expose port 80 for Nginx
EXPOSE 80

# No need to explicitly specify a command, Nginx will start automatically

