version: '3'

services:
  # Streamlit Service
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile-streamlit
    ports:
      - "8501:8501"  # Expose Streamlit app on port 8501
    networks:
      - webnet

  # Nginx Service
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "8088:8088"  # Expose Nginx on port 80
      - "8081:8081"
    volumes:
      - ./volumes/default.conf:/etc/nginx/conf.d/default.conf  # Mount the Nginx config file
      # - ./volumes/nginx.conf:/etc/nginx/nginx.conf  # Mount the Nginx config file
    depends_on:
      - streamlit  # Ensure Streamlit is started before Nginx
    networks:
      - webnet

networks:
  webnet:
    driver: bridge

